CURRENT_DATASET: "CIENCIA_DA_COMPUTACAO"

DATASETS:
  CIENCIA_DA_COMPUTACAO:
    PERIOD_RANGE: 2017_2025_1
    TRAINING_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/training/training_ciencia_da_computacao_2017_2025_1.csv
    PREPROCESSED_ACTIVE_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/preprocessed/ativos/preprocessed_ciencia_da_computacao_ativos_2017_2025_1.csv
    PREPROCESSED_DEACTIVE_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/preprocessed/inativos/preprocessed_ciencia_da_computacao_inativos_2017_2025_1.csv
    PREPROCESSED_HISTORY_DATASET: s3://pipeout-database/datasets/ciencia_da_computacao/preprocessed/historico/preprocessed_ciencia_da_computacao_historico_escolar_2017_2025_1.csv
    COLUMNS:
      MOTIVO_EVASAO_VALUE: "EXCLUSAO POR CONCLUSAO (FORMADO)"
      MOTIVO_EVASAO_COLUMN: "Situação atual"
